---
apiVersion: v1
kind: Pod
metadata:
  name: app-1.4
  labels:
    app.kubernetes.io/name: pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 80
      resources:
        limits:
          cpu: 0.2m
          memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: pod
  ports:
    - protocol: TCP
      port: 80
