apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-1.5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1.5
  template:
    metadata:
      labels:
        app: app-1.5
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 0.2m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app-1.5
  ports:
    - protocol: TCP
      port: 80
